### ISSUE TITLE
what am i doing wrong?

### ISSUE THREAD

**Issue by rubinjm** [kjaymiller/Bunch_Alfred#4]
Thanks for putting this together. I have a file named teams.bunch. When I invoke Alfred and type "b teams", I just see the file listed and not the prompt to run it.

(If I type bs I do see your Alfred workflows.)

**Comment by kjaymiller** [comment]
Did you refresh your bunches before running it?

I know there were some quirks that were causing it to not respond immediately on the first install.

**Comment by kjaymiller** [comment]
@rubinjm I just released a new version that cleans up the directory. 

The biggest change is that you will need to invoke it using the `bunch` keyword.

I did this because just using b was causing a lot of the result to run below the fold and not show up. 

![screenshot of calling bunch](https://user-images.githubusercontent.com/8632637/89647837-17c75700-d873-11ea-8f0a-0c5abedd55e8.png)

Download the latest version in the [Releases Section](https://github.com/kjaymiller/Bunch_Alfred/releases)

If you don't see your bunches still, reset your default location to the `~/bunches` folder by calling `bsettings:bunches_folder` and hitting `CMD+Return`

**Comment by rubinjm** [comment]
Thanks. Installed new version, refreshed bunches and reset default location. Still doesn't seem to work.
When I invoke it, my bunch just shows up as a file that opens in textEdit rather than being able to run it.


<img width="598" alt="Screen Shot 2020-08-07 at 1 30 29 PM" src="https://user-images.githubusercontent.com/48840674/89677043-4c0e3800-d8b2-11ea-8728-1608edbb242f.png">

**Comment by kjaymiller** [comment]
Try to reset your bunches folder using the app... I will be pushing another update that will allow you to reset the cache with bsettings:refresh. It looks like how the CLI App is storing information is a little different than the app itself.

<img width="425" alt="CleanShot 2020-08-07 at 20 45 19@2x" src="https://user-images.githubusercontent.com/8632637/89701777-ef7d3e00-d8ee-11ea-9e25-872a50bc0524.png">

I did this and then refreshed and it started working with a clean install of the workflow and the bunch application.
