### ISSUE TITLE
Wont run bunch

### ISSUE THREAD

**Issue by mikeerickson** [kjaymiller/Bunch_Alfred#5]
I am trying out this extension as per recommendation from Brett.

When I invoke Bunch from Alfred, I see the following

https://github.com/kjaymiller/Bunch_Alfred.git
![image](https://user-images.githubusercontent.com/183153/106685150-ac89e380-657c-11eb-8d85-4d0b0ae3e76c.png)

If I enter `bunch Test` (this is a test bunch script) it just wants to search internet

![image](https://user-images.githubusercontent.com/183153/106685205-c9261b80-657c-11eb-8c27-3306ae6caa0d.png)

And I am not sure what the "Run Bunch" options are supposed to do?

![image](https://user-images.githubusercontent.com/183153/106685249-e3f89000-657c-11eb-9f30-42aca0007dd4.png)

**Comment by tborychowski** [comment]
@mikeerickson 
I just created another one: https://github.com/tborychowski/bunch-alfred and see if that works for you.
You're welcome to try it out. 
I'll be happy to fix any issues you encounter :-)

**Comment by mikeerickson** [comment]
@tborychowski i will have a look and let you know it it goes 👍

**Comment by kjaymiller** [comment]
There was an issue with the bunch cli not syncing with the bunch beta on my machine (I blame Big Sur). I have an update that will be out soon that moves things to the x-callback url will sync better with the application.

**Comment by kjaymiller** [comment]
I've released a quick release that should fix this. I would recommend updating to this version which should fix the issues you were having.

**Comment by kjaymiller** [comment]
**UPDATE** Latest Version fixes major issue where configDirs would get messed up which is what I believe was the previous issue. Here is the updated version (with updated notes/documentation) I'll leave this open for a few days in case there are issues that arise. Happy to help troubleshoot. - https://github.com/kjaymiller/Bunch_Alfred/releases/2021.04.01

**Comment by mikeerickson** [comment]
@kjaymiller I have installed the latest version (as reference above) and I am still experiencing the same issue as originally reported
